languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "小熊猫站起来"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.png"
  description = "Record computer, finance, and philosophy"
  copyright = "© { year } <span class='inline-block'> Lesser Bear-Cat </span> All Rights Reserved</span>."

[author]
  name = "Suika"
  image = "img/bear-cat-logo.png"
  headline = "真正的猛兽，以站立的姿态走行世间"
  bio = "反者道之动"
  links = [
    { github = "https://github.com/LesserCat/LesserCat.github.io" },
    { envelope = "mailto:suika@kadama.eu.org" },
    { telegram = "https://t.me/sanaesbot" },
    { rss = "/index.xml" },
    { bars = "/about" },
  ]